#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

from boundingdoc.mm_agent import MMAgent
from boundingdoc.qa import (
    QAGeneratorConfig,
    QwenQAGenerator,
    build_evidence_map,
    run_qa_for_directory,
    run_qa_for_root,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate QA pairs from clean_crops images")
    parser.add_argument("--root_dir", type=Path, help="Batch mode: root directory containing report/page folders")
    parser.add_argument("--image_dir", type=Path, help="Single-directory mode: clean_crops directory")
    parser.add_argument("--model", default="Qwen/Qwen2.5-VL-7B-Instruct", help="Model name or path")
    parser.add_argument("--max_new_tokens", type=int, default=512, help="Maximum tokens generated by the QA model")
    parser.add_argument("--temperature", type=float, default=0.7, help="Sampling temperature (default: 0.7)")
    parser.add_argument("--top_p", type=float, default=0.9, help="Top-p nucleus sampling (default: 0.9)")
    parser.add_argument("--repetition_penalty", type=float, default=1.05, help="Repetition penalty (default: 1.05)")
    parser.add_argument(
        "--backend",
        choices=("hf", "vllm"),
        default="hf",
        help="Inference backend to use for QA generation (default: hf)",
    )
    parser.add_argument(
        "--batch_size",
        type=int,
        default=1,
        help="Number of crops per QA request when using the agent backend (default: 1)",
    )
    parser.add_argument(
        "--gpu_devices",
        type=str,
        help="Comma-separated GPU ids for the QA backend (applies to vLLM or single-GPU HF)",
    )
    parser.add_argument(
        "--vlm_min_pixels",
        type=int,
        default=256 * 28 * 28,
        help="Minimum pixel count used by the VLM processor (default: 200704)",
    )
    parser.add_argument(
        "--vlm_max_pixels",
        type=int,
        default=1280 * 28 * 28,
        help="Maximum pixel count used by the VLM processor (default: 1003520)",
    )
    parser.add_argument("--output", type=Path, help="Single-directory mode output JSONL path")
    parser.add_argument("--clean_summary", type=Path, help="Optional explicit path to clean_summary.json")
    return parser.parse_args()


def _parse_devices(arg: str | None) -> list[int] | None:
    if not arg:
        return None
    devices = []
    for part in arg.split(","):
        part = part.strip()
        if not part:
            continue
        devices.append(int(part))
    return devices or None


def ensure_generator(args: argparse.Namespace) -> QwenQAGenerator:
    config = QAGeneratorConfig(
        model_name=args.model,
        max_new_tokens=args.max_new_tokens,
        temperature=args.temperature,
        top_p=args.top_p,
        repetition_penalty=args.repetition_penalty,
        batch_size=args.batch_size,
    )
    agent = None
    if args.backend == "vllm":
        agent = MMAgent(
            model_name=args.model,
            use_vllm=True,
            gpu_devices=_parse_devices(args.gpu_devices),
            max_new_tokens=args.max_new_tokens,
            min_pixels=args.vlm_min_pixels,
            max_pixels=args.vlm_max_pixels,
        )
    return QwenQAGenerator(config, agent_backend=agent)


def main() -> None:
    args = parse_args()
    generator = ensure_generator(args)

    if args.root_dir:
        stats = run_qa_for_root(generator, args.root_dir, args.clean_summary, batch_size=args.batch_size)
        print(f"\nSummary: processed {stats['pages']} page(s); generated QA for {stats['images']} image(s). Root directory: {args.root_dir}")
        return

    if not args.image_dir or not args.output:
        print("ERROR: single-directory mode requires both --image_dir and --output")
        return

    evidence = build_evidence_map(args.image_dir, args.clean_summary)
    count = run_qa_for_directory(generator, args.image_dir, args.output, evidence, batch_size=args.batch_size)
    out_path = Path(args.output).with_suffix(".jsonl")
    print(f"SUCCESS: wrote {count} record(s) to {out_path}")


if __name__ == "__main__":
    main()
