#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

from boundingdoc.judge import (
    JudgeConfig,
    QwenJudge,
    post_clean,
    run_judge_directory,
    run_judge_root,
)
from boundingdoc.mm_agent import MMAgent


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Qwen2.5-VL crop quality evaluation and cleaning")
    parser.add_argument("--root_dir", type=Path, help="Batch mode: root directory containing report outputs")
    parser.add_argument("--image_dir", type=Path, help="Single-directory mode: crops directory")
    parser.add_argument("--model", default="Qwen/Qwen2.5-VL-7B-Instruct", help="Model name or path")
    parser.add_argument("--max_new_tokens", type=int, default=128, help="Maximum tokens generated by the judge model")
    parser.add_argument(
        "--backend",
        choices=("hf", "vllm"),
        default="hf",
        help="Inference backend to use for the judge model (default: hf)",
    )
    parser.add_argument(
        "--batch_size",
        type=int,
        default=1,
        help="Number of crops per judge request when using vLLM/HF agent backend (default: 1)",
    )
    parser.add_argument(
        "--gpu_devices",
        type=str,
        help="Comma-separated GPU ids for the judge backend (applies to vLLM or single-GPU HF)",
    )
    parser.add_argument(
        "--vlm_min_pixels",
        type=int,
        default=256 * 28 * 28,
        help="Minimum pixel count used by the VLM processor (default: 200704)",
    )
    parser.add_argument(
        "--vlm_max_pixels",
        type=int,
        default=1280 * 28 * 28,
        help="Maximum pixel count used by the VLM processor (default: 1003520)",
    )
    parser.add_argument("--output", type=Path, default=Path("judge_results.json"), help="Single-directory mode output path")

    parser.add_argument("--post_clean", action="store_true", help="Run cleaning only (skip model inference)")
    parser.add_argument("--judge_json", type=Path, help="post_clean mode: path to judge_results.json")
    parser.add_argument("--crops_dir", type=Path, help="post_clean mode: directory containing crops")
    parser.add_argument("--clean_output", type=Path, help="post_clean mode: directory for cleaned crops")
    parser.add_argument("--filtered_json", type=Path, help="post_clean mode: path to a single *_filtered.json")
    parser.add_argument("--filtered_json_dir", type=Path, help="post_clean mode: directory containing *_filtered.json files")
    return parser.parse_args()


def _parse_devices(arg: str | None) -> list[int] | None:
    if not arg:
        return None
    devices = []
    for part in arg.split(","):
        part = part.strip()
        if not part:
            continue
        devices.append(int(part))
    return devices or None


def ensure_judge(
    model_name: str,
    max_new_tokens: int,
    backend: str,
    gpu_devices: str | None,
    min_pixels: int,
    max_pixels: int,
    batch_size: int,
) -> QwenJudge:
    config = JudgeConfig(model_name=model_name, max_new_tokens=max_new_tokens, batch_size=batch_size)
    agent = None
    if backend == "vllm":
        agent = MMAgent(
            model_name=model_name,
            use_vllm=True,
            gpu_devices=_parse_devices(gpu_devices),
            max_new_tokens=max_new_tokens,
            min_pixels=min_pixels,
            max_pixels=max_pixels,
        )
    return QwenJudge(config, agent_backend=agent)


def rename_if_needed(output_dir: Path, desired_path: Path) -> None:
    default_path = output_dir / "judge_results.json"
    if default_path == desired_path:
        return
    desired_path.parent.mkdir(parents=True, exist_ok=True)
    if default_path.exists():
        default_path.replace(desired_path)


def main() -> None:
    args = parse_args()

    if args.root_dir:
        root = args.root_dir
        if not root.is_dir():
            print(f"ERROR: root directory does not exist: {root}")
            return
        judge = ensure_judge(
            model_name=args.model,
            max_new_tokens=args.max_new_tokens,
            backend=args.backend,
            gpu_devices=args.gpu_devices,
            min_pixels=args.vlm_min_pixels,
            max_pixels=args.vlm_max_pixels,
            batch_size=args.batch_size,
        )
        totals = run_judge_root(root, judge, post_clean_only=args.post_clean, batch_size=args.batch_size)
        print(
            f"\nSummary: processed {totals['pages']} page(s); evaluated {totals['images']} image(s); "
            f"kept {totals['clean_kept']} crop(s) after cleaning. Root directory: {root}"
        )
        types = totals["type_counts"]
        print(
            f"   ├─ keep=true: {totals['keep_true']} ; keep=false: {totals['keep_false']}\n"
            f"   └─ type distribution: text={types['text']}, table={types['table']}, "
            f"image={types['image']}, unknown={types['unknown']}"
        )
        return

    if args.post_clean:
        if not (args.judge_json and args.crops_dir and args.clean_output):
            print("ERROR: post_clean mode requires --judge_json, --crops_dir, and --clean_output")
            return
        post_clean(
            judge_json=args.judge_json,
            crops_dir=args.crops_dir,
            output_dir=args.clean_output,
            filtered_json=args.filtered_json,
            filtered_dir=args.filtered_json_dir,
        )
        return

    if not args.image_dir:
        print("ERROR: provide either --root_dir (batch mode) or --image_dir (single-directory mode)")
        return

    image_dir = args.image_dir
    if not image_dir.is_dir():
        print(f"ERROR: directory does not exist: {image_dir}")
        return

    judge = ensure_judge(
        model_name=args.model,
        max_new_tokens=args.max_new_tokens,
        backend=args.backend,
        gpu_devices=args.gpu_devices,
        min_pixels=args.vlm_min_pixels,
        max_pixels=args.vlm_max_pixels,
        batch_size=args.batch_size,
    )
    output_dir = args.output.parent if args.output.parent != Path() else Path(".")
    results = run_judge_directory(image_dir, judge, output_dir, batch_size=args.batch_size)
    rename_if_needed(output_dir, args.output)
    print(f"\nEvaluation complete for {len(results)} image(s). Results saved to: {args.output}")


if __name__ == "__main__":
    main()
